# Generated by Django 4.2.2 on 2023-06-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
