# Generated by Django 4.2.2 on 2023-07-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='celular',
            field=models.CharField(default='', max_length=11),
        ),
    ]
