# Generated by Django 4.2.2 on 2023-07-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_aluno_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
